replicaCount: 3

image:
  repository: host.docker.internal:8082/python-demo-app
  tag: "57b35bd2f88de2d3e916d919e5ba801c98b2be62"

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 500m
    memory: 512Mi