replicaCount: 3

image:
  repository: artifact.registry.com:8082/python-demo-app
  tag: "324a03b554253cfb9b19ed453402ef0895d42859"

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 500m
    memory: 512Mi