replicaCount: 3

image:
  repository: artifact.registry.com:8082/python-demo-app
  tag: "3b5358d9a2075a6cb2a165102fb9028fa40441b5"

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 500m
    memory: 512Mi